application: your-app-id
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Server
- url: /_ah/spi/.*
  script: main.APPLICATION

# Client
- url: /favicon\.ico
  static_files: client/assets/img/favicon.ico
  upload: client/assets/img/favicon\.ico

- url: /client/(.*)
  static_files: client/\1
  upload: client/.*\.(js|html)

- url: /css
  static_dir: client/assets/css

- url: /img
  static_dir: client/assets/img

- url: /.*
  static_files: client/index.html
  upload: client/index.html

libraries:
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest
